// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIF1qUt27qMlRl7CqwZ3Wkr_2VTAFYPew',
    appId: '1:871287884710:web:55afbe40b0d7af871fdd67',
    messagingSenderId: '871287884710',
    projectId: 'krl-goon-authentication',
    authDomain: 'krl-goon-authentication.firebaseapp.com',
    storageBucket: 'krl-goon-authentication.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4NLOx9fNowOsLYstHX54MufgiT9JevaI',
    appId: '1:871287884710:android:80413dd97fe6ffbb1fdd67',
    messagingSenderId: '871287884710',
    projectId: 'krl-goon-authentication',
    storageBucket: 'krl-goon-authentication.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1AVrbPBfvmqJUpflFOuiA8rM-MFX6ogo',
    appId: '1:871287884710:ios:be0fbf5f80b366541fdd67',
    messagingSenderId: '871287884710',
    projectId: 'krl-goon-authentication',
    storageBucket: 'krl-goon-authentication.appspot.com',
    androidClientId: '871287884710-sqp496oo53ug6edm2f5oio95n7rbosng.apps.googleusercontent.com',
    iosClientId: '871287884710-s37ct5lg63epv1g8otorpr8jk1d7cooc.apps.googleusercontent.com',
    iosBundleId: 'com.example.ericoTutorials',
  );
}
